version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    image: 792520190064.dkr.ecr.ap-south-1.amazonaws.com/concierge/frontend:02
    container_name: concierge-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
